## **Step 1. 데이터 불러오기**

In [ ]:
# drive에 연결합니다.
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

# 현재 데이터가 있는 공간으로 작업 경로를 변경해줍니다.
%cd "/content/drive/MyDrive/AI/Data Set/신용카드_사용자 연체 예측"

Mounted at /content/drive
/content/drive/MyDrive/AI/Data Set/신용카드_사용자 연체 예측

In [ ]:
# pandas 패키지를 pd라는 별칭으로 불러옵니다.
import pandas as pd

# sample_submission.csv 파일을 submission이라는 변수에 할당합니다.
submission = pd.read_csv('sample_submission.csv')

In [ ]:
# pandas 패키지를 pd 라는 별칭으로 import 해봅시다!
import pandas as pd

# pandas 내에 있는 read_csv 함수를 사용해 train.csv, test.csv 파일을 각각 train, test라는 이름으로 불러와봅시다!
train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')

## **Step 2. 간단하게 데이터 살펴보기**

In [ ]:
submission.head()

   index  0  1  2
0  26457  0  0  0
1  26458  0  0  0
2  26459  0  0  0
3  26460  0  0  0
4  26461  0  0  0

In [ ]:
# train 데이터의 하위 행 5개를 확인합니다.
train.tail()

,index,gender,car,reality,child_num,income_total,income_type,edu_type,family_type,house_type,DAYS_BIRTH,DAYS_EMPLOYED,FLAG_MOBIL,work_phone,phone,email,occyp_type,family_size,begin_month,credit
26452,26452,F,N,N,2,225000.0,State servant,Secondary / secondary special,Married,House / apartment,1.864518e-09,0.0,1,0,0,0,Core staff,4.0,2.0,1.0
26453,26453,F,N,Y,1,180000.0,Working,Higher education,Separated,House / apartment,2.360324e-09,0.0,1,0,0,0,No job,2.0,47.0,2.0
26454,26454,F,Y,N,0,292500.0,Working,Secondary / secondary special,Civil marriage,With parents,1.556261e-09,0.0,1,0,0,0,Core staff,2.0,25.0,2.0
26455,26455,M,N,Y,0,171000.0,Working,Incomplete higher,Single / not married,House / apartment,1.565985e-09,0.0,1,0,0,0,Laborers,1.0,59.0,2.0
26456,26456,F,N,N,0,81000.0,Working,Secondary / secondary special,Civil marriage,House / apartment,3.020677e-09,0.0,1,0,0,0,Security staff,2.0,9.0,2.0

### **2. columns**

In [ ]:
# train 데이터의 컬럼들을 확인합니다.
train.columns

Index(['index', 'gender', 'car', 'reality', 'child_num', 'income_total',
       'income_type', 'edu_type', 'family_type', 'house_type', 'DAYS_BIRTH',
       'DAYS_EMPLOYED', 'FLAG_MOBIL', 'work_phone', 'phone', 'email',
       'occyp_type', 'family_size', 'begin_month', 'credit'],
      dtype='object')

### train 데이터의 컬럼은 다음과 같습니다.
* index
* gender: 성별
* car: 차량 소유 여부
* reality: 부동산 소유 여부
* child_num: 자녀 수
* income_total: 연간 소득
* income_type: 소득 분류
							['Commercial associate', 'Working', 'State servant', 'Pensioner', 'Student']

* edu_type: 교육 수준
							['Higher education' ,'Secondary / secondary special', 'Incomplete higher', 'Lower secondary', 'Academic degree']

* family_type: 결혼 여부
							['Married', 'Civil marriage', 'Separated', 'Single / not married', 'Widow']

* house_type: 생활 방식
							['Municipal apartment', 'House / apartment', 'With parents',

							 'Co-op apartment', 'Rented apartment', 'Office apartment']

* DAYS_BIRTH: 출생일
							데이터 수집 당시 (0)부터 역으로 셈, 즉, -1은 데이터 수집일 하루 전에 태어났음을 의미

* DAYS_EMPLOYED: 업무 시작일
							데이터 수집 당시 (0)부터 역으로 셈, 즉, -1은 데이터 수집일 하루 전부터 일을 시작함을 의미

							양수 값은 고용되지 않은 상태를 의미함

* FLAG_MOBIL: 핸드폰 소유 여부
* work_phone: 업무용 전화 소유 여부
* phone: 전화 소유 여부
* email: 이메일 소유 여부
* occyp_type: 직업 유형
* family_size: 가족 규모
* begin_month: 신용카드 발급 월
							데이터 수집 당시 (0)부터 역으로 셈, 즉, -1은 데이터 수집일 한 달 전에 신용카드를 발급함을 의미

* credit: 사용자의 신용카드 대금 연체를 기준으로 한 신용도
							=> 낮을 수록 높은 신용의 신용카드 사용자를 의미함

In [ ]:
# train 데이터의 행과 열의 개수를 확인합니다.
train.shape

(26457, 20)